.TH "DrawingVisitor" 3 "Thu Nov 17 2016" "Version 1" "Drawing Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DrawingVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DrawingVisitor\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdraw\fP (\fBCircle\fP *circle)=0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (Segment *segment)=0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (Triangle *triangle)=0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (Polygon *polygon)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void DrawingVisitor::draw (\fBCircle\fP * circle)\fC [pure virtual]\fP"

.SS "virtual void DrawingVisitor::draw (Segment * segment)\fC [pure virtual]\fP"

.SS "virtual void DrawingVisitor::draw (Triangle * triangle)\fC [pure virtual]\fP"

.SS "virtual void DrawingVisitor::draw (Polygon * polygon)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Drawing Client from the source code\&.
