.TH "src/test-vector2D.cpp" 3 "Thu Nov 17 2016" "Version 1" "Drawing Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test-vector2D.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Vector2D\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Drawing Client from the source code\&.
