.TH "src/Vector2D.hpp" 3 "Thu Nov 17 2016" "Version 1" "Drawing Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Vector2D.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector2D\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBVector2D\fP \fBoperator*\fP (const double &a, const \fBVector2D\fP &vector)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBVector2D\fP &vector)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBVector2D\fP operator* (const double & a, const \fBVector2D\fP & vector)"

.SS "ostream& operator<< (ostream & os, const \fBVector2D\fP & vector)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Drawing Client from the source code\&.
